import { Character } from "./character";

export const CHARACTERS:  Character[] = [
  {
    "id": 10,
    "name": 'Tim',
    "level": 1,
    "strength": 10,
    "dexterity": 10,
    "constitution": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charisma": 10,
    "maxHP": 10,
    "ac": 10,
    "speed": 10,
    "resistances": "keine",
    "immunities": "keine",
    "passivePerception": 10,
    "languages": "keine"
  },
  {
    "id": 11,
    "name": 'Sascha',
    "level": 2,
    "strength": 11,
    "dexterity": 11,
    "constitution": 11,
    "intelligence": 11,
    "wisdom": 11,
    "charisma": 11,
    "maxHP": 11,
    "ac": 11,
    "speed": 11,
    "resistances": "eine",
    "immunities": "eine",
    "passivePerception": 11,
    "languages": "eine"
  },
  {id: 12, name: 'Theadius'},
  {id: 13, name: 'Sir Tinly'},
  {id: 14, name: 'Brody'},
  {id: 15, name: 'Sascha'},
  {id: 16, name: 'Reinhardt'},
  {id: 17, name: 'Enoch'},
  {id: 18, name: 'Martin'},
  {id: 19, name: 'Ludwig'},
  {id: 20, name: 'Jan'},
]
